### ISSUE TITLE
Does CPU refer to GPU?

### ISSUE THREAD

**Issue by nathankg** [m1guelpf/cog-rust#3]
In the given examples, only the stable diffusion example has the `CPU` metadata field set to `True`. And I know that in replicate's cog package, they have a `GPU` parameter. Would we set `CPU` to true here if our model requires a base image with gpu capability?

Thanks!

https://github.com/m1guelpf/cog-rust/blob/1d54c036d8958cce21b6673e8033be3c935fa6be/examples/stable-diffusion/Cargo.toml#L9

**Comment by m1guelpf** [comment]
Whoops no this should be GPU, fixed here: https://github.com/m1guelpf/cog-rust/commit/0fc0954c07c206796f22572f1928ce695c9f7ea2
